### ISSUE TITLE
Throws an error when optimizing

### ISSUE THREAD

**Issue by danmillar** [vikseriq/requirejs-vue#1]
This is a great plugin and works well. I'm having an issue however when trying to use the requirejs optimizer (r.js -o). It fails at the plugin with an error of "Unsupported environment". Any ideas?

**Comment by vikseriq** [comment]
Currently aimed to work only in browser environment with XMLHttpRequest enabled (so no IE6 too).
PR for server-side execution (node/r.js -o) are welcome :)

**Comment by vikseriq** [comment]
Now plugin supports `r.js` building workflow. Enjoy!
